# Generated by Django 3.2.8 on 2021-11-18 01:35
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('health', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appoint',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='service',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.DeleteModel(
            name='Medical_Record',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
